services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: timeline-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/timeline.db
      - SECRET_KEY=timeline-production-secret-key-change-this
      - UPLOAD_FOLDER=/app/static/uploads
      - MAX_CONTENT_LENGTH=16777216
      - CORS_ORIGINS=http://xn--cpq55e94lgvdcukyqt.com,http://张伟爱刘新宇.com,https://xn--cpq55e94lgvdcukyqt.com,https://张伟爱刘新宇.com
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - timeline-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.server
    container_name: timeline-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx-http.conf:/etc/nginx/conf.d/default.conf
      - ./static/uploads:/usr/share/nginx/html/uploads
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - timeline-network

networks:
  timeline-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
