services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: timeline-backend
    volumes:
      - timeline-data:/app/data
      - timeline-uploads:/app/static/uploads
      - timeline-logs:/app/logs
    env_file:
      - .env.production
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/timeline.db
      - UPLOAD_FOLDER=/app/static/uploads
      - PORT=5000
    restart: unless-stopped
    networks:
      - timeline-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.production
    container_name: timeline-frontend
    restart: unless-stopped
    networks:
      - timeline-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx代理服务
  nginx:
    image: nginx:alpine
    container_name: timeline-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - timeline-uploads:/var/www/static/uploads:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - timeline-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  timeline-network:
    driver: bridge

volumes:
  timeline-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  timeline-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static/uploads
  timeline-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  nginx-cache:
    driver: local